# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_parser', '0002_auto_20170112_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200)),
                ('last_name', models.CharField(blank=True, max_length=200)),
                ('email', models.TextField(blank=True)),
                ('domain', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
