# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_parser', '0003_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
