# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_parser', '0004_auto_20170113_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
