# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_parser', '0006_auto_20170113_1710'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Csv',
            new_name='CsvList',
        ),
    ]
